name: C++ Code Check

on:
  push:
  pull_request:


jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.14.0
      with:
        clang-format-version: '18'
        check-path: 'tirpc'

  cppcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
    - name: Run cppcheck
      run: |
        cppcheck ./tirpc --quiet --enable=style,warning,performance,portability --inconclusive --error-exitcode=1
